<?php 
$fn=$_POST['firstname']; 
$sex=$_POST['sex'];
$bday=$_POST['bday'];
$Qu=$_POST['Qu'];
$usremail=$_POST['usremail'];
$exp=$_POST['exp'];
$points=$_POST['points'];
$favcolor=$_POST['favcolor'];
$addr=$_POST['addr'];
$state=$_POST['state'];
$vehicle=$_POST['vehicle'];
$homepage=$_POST['homepage'];
echo $fn; 
echo "<br>";
echo $sex;
echo "<br>";
echo $bday;
echo "<br>";
echo $Qu;
echo "<br>";
echo $usremail;
echo "<br>";
echo $exp;
echo "<br>";
echo $points;
echo "<br>";
echo $favcolor;
echo "<br>";
echo $addr;
echo "<br>";
echo $state;
echo "<br>";
echo $vehicle;
echo "<br>";
echo $homepage;
?>
